name: PATHFACTORY e2e tests
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Cypress tests
        uses: cypress-io/github-action@v4.2.0
        with:
          install-command: npm install
          command: npm run cy:run
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: cypress/reports/